[build]
builder = "python"

[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python -m pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python run.py"